## 30s k-fold

In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv1D, MaxPooling1D, AveragePooling1D, Dropout
from keras.layers import Activation, BatchNormalization
from keras.optimizers import Adam
from keras.utils import np_utils
import tensorflow as tf
from keras.callbacks import TensorBoard, EarlyStopping
np.set_printoptions(suppress=True)

trainD = np.load("/home/hsiehch/30s/train_data.npy")
trainL = np.load("/home/hsiehch/30s/train_label.npy")
validationD = np.load("/home/hsiehch/30s/validation_data.npy")
validationL = np.load("/home/hsiehch/30s/validation_label.npy")
testD = np.load("/home/hsiehch/30s/test_data.npy")
testL = np.load("/home/hsiehch/30s/test_label.npy")

trainD = np.append(trainD, validationD, axis=0)
trainL = np.append(trainL, validationL, axis=0)
trainD = np.append(trainD, testD, axis=0)
trainL = np.append(trainL, testL, axis=0)

trainData = trainD.reshape((trainD.shape[0], trainD.shape[1], 1))
trainLabel = np_utils.to_categorical(trainL, 4)
print('Train Data:', trainData.shape)
print('Train Label: ', trainLabel.shape)

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


Train Data: (10151, 9000, 1)
Train Label:  (10151, 4)


In [2]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=5, shuffle=True)
print(kf)

training_data = []
training_label = []
validation_cate_label = []
validation_data = []
validation_label = []

for train_index, test_index in kf.split(trainData):
    print('trian:', train_index, 'len', len(train_index), 'test:', test_index, 'len', len(test_index))
    training_data.append(trainData[train_index])
    training_label.append(trainLabel[train_index])
    validation_data.append(trainData[test_index])
    validation_label.append(trainLabel[test_index])
    validation_cate_label.append(trainL[test_index])

training_data = np.array(training_data)
training_label = np.array(training_label)
validation_data = np.array(validation_data)
validation_label = np.array(validation_label)
validation_cate_label = np.array(validation_cate_label)


KFold(n_splits=5, random_state=None, shuffle=True)
trian: [    2     5     6 ... 10148 10149 10150] len 8120 test: [    0     1     3 ... 10128 10135 10146] len 2031
trian: [    0     1     3 ... 10148 10149 10150] len 8121 test: [    2    11    13 ... 10140 10141 10143] len 2030
trian: [    0     1     2 ... 10146 10148 10150] len 8121 test: [    5    14    17 ... 10145 10147 10149] len 2030
trian: [    0     1     2 ... 10146 10147 10149] len 8121 test: [    7    10    20 ... 10139 10148 10150] len 2030
trian: [    0     1     2 ... 10148 10149 10150] len 8121 test: [    6     9    31 ... 10134 10138 10142] len 2030


In [3]:
training_data[0].shape

(8120, 9000, 1)

In [4]:
from sklearn.metrics import f1_score
import pandas as pd
from sklearn.model_selection import GridSearchCV
from keras.wrappers.scikit_learn import KerasClassifier
import itertools

def create_model():
    model = Sequential() 
    model.add(Conv1D(filters = 32, kernel_size = 7, input_shape = (trainData.shape[1], 1)))
    model.add(Activation('relu'))
    model.add(BatchNormalization())
    model.add(MaxPooling1D(pool_size = 2))

    model.add(Conv1D(filters = 32, kernel_size = 7))
    model.add(Activation('relu'))
    model.add(MaxPooling1D(pool_size = 2))

    model.add(Conv1D(filters = 64, kernel_size = 7))
    model.add(Activation('relu'))
    model.add(MaxPooling1D(pool_size = 2))

    model.add(Conv1D(filters = 64, kernel_size = 3))
    model.add(Activation('relu'))
    model.add(MaxPooling1D(pool_size = 2))

    model.add(Conv1D(filters = 128, kernel_size = 3))
    model.add(Activation('relu'))
    model.add(MaxPooling1D(pool_size = 2))

    model.add(Conv1D(filters = 128, kernel_size = 3))
    model.add(Activation('relu'))
    model.add(MaxPooling1D(pool_size = 2))
    model.add(Dropout(0.5))

    model.add(Conv1D(filters = 256, kernel_size = 3))
    model.add(Activation('relu'))
    model.add(MaxPooling1D(pool_size = 2))

    model.add(Conv1D(filters = 256, kernel_size = 3))
    model.add(Activation('relu'))
    model.add(MaxPooling1D(pool_size = 2))
    model.add(Dropout(0.5))

    model.add(Conv1D(filters = 512, kernel_size = 3))
    model.add(Activation('relu'))
    model.add(MaxPooling1D(pool_size = 2))
    model.add(Dropout(0.5))

    model.add(Conv1D(filters = 512, kernel_size = 3))
    model.add(Activation('relu'))

    model.add(Flatten())
    model.add(Dense(128, activation = 'relu'))
    model.add(Dropout(0.5))
    model.add(Dense(32, activation = 'relu'))
    model.add(Dense(4, activation = "softmax"))

    return model

def calculate_avg_F1(scores):
    tmp = [0,0,0,0]
    for i in scores:
        tmp += i
    tmp /= 5
    return tmp

def run_model(batch_S, learning_rate=0.001):
    
    Scores = []
    for X_train, Y_train, X_val, Y_val, val_cat in zip(training_data, training_label, validation_data, validation_label, validation_cate_label):

        model = create_model()
        adam = Adam(lr = learning_rate)
        model.compile(optimizer = adam, loss = "categorical_crossentropy", metrics=['accuracy'])
        early_stop = EarlyStopping(patience=20)
        train_history_1 = model.fit(x = X_train, 
                                    y = Y_train,
                                    epochs=80,
                                    validation_data=(X_val, Y_val),
                                    callbacks=[early_stop],
                                    batch_size=batch_S, 
                                    verbose=1)
        evaluation = model.evaluate(x = X_val, y = Y_val)
        print('Loss: {:.3f}, Accuracy: {:.3f}'.format(evaluation[0], evaluation[1]))

        validation_prediction = model.predict_classes(X_val, batch_size=batch_S)
        score = f1_score(val_cat, validation_prediction, average=None)
        Scores.append(score)
        del model
    
    result = calculate_avg_F1(Scores)
    F1_result.append(result)
    del Scores
    

        
F1_result = []
hyperparameter_index = []
batch_S = [70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80]

for bat in batch_S:
    hyperparameter_index.append([bat])
    run_model(bat)

print('Finish training!')

Train on 8120 samples, validate on 2031 samples
Epoch 1/80
8120/8120 [==============================] - 14s 2ms/step - loss: 1.0419 - acc: 0.5698 - val_loss: 0.9277 - val_acc: 0.6032
Epoch 2/80
8120/8120 [==============================] - 7s 912us/step - loss: 0.8911 - acc: 0.5924 - val_loss: 0.8599 - val_acc: 0.6460
Epoch 3/80
8120/8120 [==============================] - 8s 955us/step - loss: 0.7992 - acc: 0.6499 - val_loss: 0.7201 - val_acc: 0.6982
Epoch 4/80
8120/8120 [==============================] - 8s 950us/step - loss: 0.6983 - acc: 0.7028 - val_loss: 0.7094 - val_acc: 0.7420
Epoch 5/80
8120/8120 [==============================] - 8s 959us/step - loss: 0.6504 - acc: 0.7361 - val_loss: 0.6336 - val_acc: 0.7627
Epoch 6/80
8120/8120 [==============================] - 8s 959us/step - loss: 0.5895 - acc: 0.7676 - val_loss: 0.6580 - val_acc: 0.7696
Epoch 7/80
8120/8120 [==============================] - 8s 947us/step - loss: 0.5756 - acc: 0.7754 - val_loss: 0.5368 - val_acc: 0.8016
E

8121/8121 [==============================] - 8s 965us/step - loss: 0.5830 - acc: 0.7681 - val_loss: 0.4954 - val_acc: 0.8084
Epoch 11/80
8121/8121 [==============================] - 8s 975us/step - loss: 0.5373 - acc: 0.7884 - val_loss: 0.4870 - val_acc: 0.8084
Epoch 12/80
8121/8121 [==============================] - 8s 972us/step - loss: 0.5246 - acc: 0.8009 - val_loss: 0.4456 - val_acc: 0.8315
Epoch 13/80
8121/8121 [==============================] - 8s 979us/step - loss: 0.5134 - acc: 0.8080 - val_loss: 0.5481 - val_acc: 0.7911
Epoch 14/80
8121/8121 [==============================] - 8s 971us/step - loss: 0.5781 - acc: 0.7657 - val_loss: 0.4458 - val_acc: 0.8330
Epoch 15/80
8121/8121 [==============================] - 8s 966us/step - loss: 0.4978 - acc: 0.8132 - val_loss: 0.4537 - val_acc: 0.8261
Epoch 16/80
8121/8121 [==============================] - 8s 952us/step - loss: 0.4728 - acc: 0.8227 - val_loss: 0.4513 - val_acc: 0.8345
Epoch 17/80
8121/8121 [==============================

Epoch 8/80
8121/8121 [==============================] - 8s 964us/step - loss: 0.5624 - acc: 0.7825 - val_loss: 0.5310 - val_acc: 0.7980
Epoch 9/80
8121/8121 [==============================] - 8s 963us/step - loss: 0.5386 - acc: 0.7990 - val_loss: 0.5228 - val_acc: 0.8039
Epoch 10/80
8121/8121 [==============================] - 8s 969us/step - loss: 0.5163 - acc: 0.8041 - val_loss: 0.5354 - val_acc: 0.8148
Epoch 11/80
8121/8121 [==============================] - 8s 933us/step - loss: 0.4970 - acc: 0.8164 - val_loss: 0.5042 - val_acc: 0.8128
Epoch 12/80
8121/8121 [==============================] - 8s 973us/step - loss: 0.4889 - acc: 0.8211 - val_loss: 0.4922 - val_acc: 0.8246
Epoch 13/80
8121/8121 [==============================] - 8s 962us/step - loss: 0.4796 - acc: 0.8256 - val_loss: 0.4966 - val_acc: 0.8197
Epoch 14/80
8121/8121 [==============================] - 8s 936us/step - loss: 0.4630 - acc: 0.8317 - val_loss: 0.4709 - val_acc: 0.8365
Epoch 15/80
8121/8121 [====================

Epoch 16/80
8121/8121 [==============================] - 8s 936us/step - loss: 0.4938 - acc: 0.8158 - val_loss: 0.4597 - val_acc: 0.8300
Epoch 17/80
8121/8121 [==============================] - 8s 970us/step - loss: 0.4461 - acc: 0.8346 - val_loss: 0.4849 - val_acc: 0.8138
Epoch 18/80
8121/8121 [==============================] - 8s 929us/step - loss: 0.4485 - acc: 0.8366 - val_loss: 0.4624 - val_acc: 0.8266
Epoch 19/80
8121/8121 [==============================] - 8s 968us/step - loss: 0.4307 - acc: 0.8414 - val_loss: 0.4823 - val_acc: 0.8251
Epoch 20/80
8121/8121 [==============================] - 8s 933us/step - loss: 0.4280 - acc: 0.8446 - val_loss: 0.4707 - val_acc: 0.8355
Epoch 21/80
8121/8121 [==============================] - 8s 962us/step - loss: 0.4202 - acc: 0.8478 - val_loss: 0.5468 - val_acc: 0.8172
Epoch 22/80
8121/8121 [==============================] - 8s 939us/step - loss: 0.4776 - acc: 0.8189 - val_loss: 0.5942 - val_acc: 0.7828
Epoch 23/80
8121/8121 [==================

Epoch 76/80
2030/2030 [==============================] - 1s 326us/step
Loss: 0.466, Accuracy: 0.845
Train on 8121 samples, validate on 2030 samples
Epoch 1/80
8121/8121 [==============================] - 10s 1ms/step - loss: 0.9990 - acc: 0.5780 - val_loss: 0.9022 - val_acc: 0.5872
Epoch 2/80
8121/8121 [==============================] - 8s 948us/step - loss: 0.8909 - acc: 0.6145 - val_loss: 0.7973 - val_acc: 0.6576
Epoch 3/80
8121/8121 [==============================] - 8s 954us/step - loss: 0.7889 - acc: 0.6645 - val_loss: 0.6857 - val_acc: 0.7059
Epoch 4/80
8121/8121 [==============================] - 8s 928us/step - loss: 0.7135 - acc: 0.7030 - val_loss: 0.6501 - val_acc: 0.7355
Epoch 5/80
8121/8121 [==============================] - 8s 931us/step - loss: 0.6229 - acc: 0.7537 - val_loss: 0.7545 - val_acc: 0.6966
Epoch 6/80
8121/8121 [==============================] - 8s 931us/step - loss: 0.6003 - acc: 0.7639 - val_loss: 0.5499 - val_acc: 0.7857
Epoch 7/80
8121/8121 [===============

Epoch 16/80
8120/8120 [==============================] - 8s 992us/step - loss: 0.4331 - acc: 0.8384 - val_loss: 0.5067 - val_acc: 0.8208
Epoch 17/80
8120/8120 [==============================] - 8s 993us/step - loss: 0.4287 - acc: 0.8446 - val_loss: 0.4901 - val_acc: 0.8257
Epoch 18/80
8120/8120 [==============================] - 8s 998us/step - loss: 0.4195 - acc: 0.8466 - val_loss: 0.4896 - val_acc: 0.8139
Epoch 19/80
8120/8120 [==============================] - 8s 988us/step - loss: 0.4254 - acc: 0.8436 - val_loss: 0.4844 - val_acc: 0.8198
Epoch 20/80
8120/8120 [==============================] - 8s 989us/step - loss: 0.4163 - acc: 0.8477 - val_loss: 0.4593 - val_acc: 0.8346
Epoch 21/80
8120/8120 [==============================] - 8s 984us/step - loss: 0.4123 - acc: 0.8521 - val_loss: 0.4629 - val_acc: 0.8351
Epoch 22/80
8120/8120 [==============================] - 8s 980us/step - loss: 0.3912 - acc: 0.8550 - val_loss: 0.4641 - val_acc: 0.8272
Epoch 23/80
8120/8120 [==================

Epoch 24/80
8121/8121 [==============================] - 8s 997us/step - loss: 0.4247 - acc: 0.8484 - val_loss: 0.4439 - val_acc: 0.8419
Epoch 25/80
8121/8121 [==============================] - 8s 994us/step - loss: 0.4144 - acc: 0.8503 - val_loss: 0.4210 - val_acc: 0.8478
Epoch 26/80
8121/8121 [==============================] - 8s 983us/step - loss: 0.4136 - acc: 0.8488 - val_loss: 0.4038 - val_acc: 0.8517
Epoch 27/80
8121/8121 [==============================] - 8s 994us/step - loss: 0.4073 - acc: 0.8524 - val_loss: 0.4176 - val_acc: 0.8468
Epoch 28/80
8121/8121 [==============================] - 8s 981us/step - loss: 0.4046 - acc: 0.8503 - val_loss: 0.4264 - val_acc: 0.8443
Epoch 29/80
8121/8121 [==============================] - 8s 977us/step - loss: 0.3978 - acc: 0.8516 - val_loss: 0.4283 - val_acc: 0.8512
Epoch 30/80
8121/8121 [==============================] - 8s 989us/step - loss: 0.3838 - acc: 0.8623 - val_loss: 0.4478 - val_acc: 0.8448
Epoch 31/80
8121/8121 [==================

8121/8121 [==============================] - 10s 1ms/step - loss: 1.0111 - acc: 0.5807 - val_loss: 0.9023 - val_acc: 0.5660
Epoch 2/80
8121/8121 [==============================] - 8s 972us/step - loss: 0.8873 - acc: 0.6121 - val_loss: 0.8354 - val_acc: 0.6158
Epoch 3/80
8121/8121 [==============================] - 8s 970us/step - loss: 0.7903 - acc: 0.6578 - val_loss: 0.7571 - val_acc: 0.7064
Epoch 4/80
8121/8121 [==============================] - 8s 967us/step - loss: 0.7079 - acc: 0.7074 - val_loss: 0.7080 - val_acc: 0.7340
Epoch 5/80
8121/8121 [==============================] - 8s 977us/step - loss: 0.6569 - acc: 0.7343 - val_loss: 0.6408 - val_acc: 0.7409
Epoch 6/80
8121/8121 [==============================] - 8s 972us/step - loss: 0.6297 - acc: 0.7478 - val_loss: 0.6136 - val_acc: 0.7793
Epoch 7/80
8121/8121 [==============================] - 8s 963us/step - loss: 0.6007 - acc: 0.7642 - val_loss: 0.5665 - val_acc: 0.7892
Epoch 8/80
8121/8121 [==============================] - 8s 9

Epoch 61/80
8121/8121 [==============================] - 8s 968us/step - loss: 0.2886 - acc: 0.8923 - val_loss: 0.4607 - val_acc: 0.8365
Epoch 62/80
8121/8121 [==============================] - 8s 979us/step - loss: 0.2928 - acc: 0.8891 - val_loss: 0.4459 - val_acc: 0.8478
Epoch 63/80
8121/8121 [==============================] - 8s 968us/step - loss: 0.2881 - acc: 0.8953 - val_loss: 0.4684 - val_acc: 0.8424
Epoch 64/80
8121/8121 [==============================] - 8s 981us/step - loss: 0.2752 - acc: 0.9025 - val_loss: 0.4782 - val_acc: 0.8389
Epoch 65/80
8121/8121 [==============================] - 8s 978us/step - loss: 0.2707 - acc: 0.9036 - val_loss: 0.4677 - val_acc: 0.8438
Epoch 66/80
2030/2030 [==============================] - 1s 330us/step
Loss: 0.498, Accuracy: 0.835
Train on 8121 samples, validate on 2030 samples
Epoch 1/80
8121/8121 [==============================] - 10s 1ms/step - loss: 0.9951 - acc: 0.5710 - val_loss: 0.9313 - val_acc: 0.5872
Epoch 2/80
8121/8121 [==========

Epoch 7/80
8120/8120 [==============================] - 8s 978us/step - loss: 0.5666 - acc: 0.7817 - val_loss: 0.5389 - val_acc: 0.7962
Epoch 8/80
8120/8120 [==============================] - 8s 979us/step - loss: 0.5396 - acc: 0.7919 - val_loss: 0.5286 - val_acc: 0.8050
Epoch 9/80
8120/8120 [==============================] - 8s 996us/step - loss: 0.5106 - acc: 0.8039 - val_loss: 0.5133 - val_acc: 0.8011
Epoch 10/80
8120/8120 [==============================] - 8s 986us/step - loss: 0.4916 - acc: 0.8126 - val_loss: 0.5137 - val_acc: 0.8090
Epoch 11/80
8120/8120 [==============================] - 8s 989us/step - loss: 0.4795 - acc: 0.8248 - val_loss: 0.5095 - val_acc: 0.8104
Epoch 12/80
8120/8120 [==============================] - 8s 988us/step - loss: 0.4823 - acc: 0.8207 - val_loss: 0.5017 - val_acc: 0.8149
Epoch 13/80
8120/8120 [==============================] - 8s 1ms/step - loss: 0.4501 - acc: 0.8344 - val_loss: 0.4694 - val_acc: 0.8237
Epoch 14/80
8120/8120 [=======================

Epoch 15/80
8121/8121 [==============================] - 8s 939us/step - loss: 0.4651 - acc: 0.8296 - val_loss: 0.4186 - val_acc: 0.8473
Epoch 16/80
8121/8121 [==============================] - 8s 938us/step - loss: 0.4555 - acc: 0.8393 - val_loss: 0.4405 - val_acc: 0.8345
Epoch 17/80
8121/8121 [==============================] - 8s 969us/step - loss: 0.4453 - acc: 0.8413 - val_loss: 0.4295 - val_acc: 0.8384
Epoch 18/80
8121/8121 [==============================] - 8s 983us/step - loss: 0.4397 - acc: 0.8381 - val_loss: 0.4254 - val_acc: 0.8458
Epoch 19/80
8121/8121 [==============================] - 8s 975us/step - loss: 0.4325 - acc: 0.8409 - val_loss: 0.4469 - val_acc: 0.8433
Epoch 20/80
8121/8121 [==============================] - 8s 965us/step - loss: 0.4215 - acc: 0.8458 - val_loss: 0.4068 - val_acc: 0.8502
Epoch 21/80
8121/8121 [==============================] - 8s 967us/step - loss: 0.4089 - acc: 0.8511 - val_loss: 0.4306 - val_acc: 0.8493
Epoch 22/80
8121/8121 [==================

Epoch 34/80
8121/8121 [==============================] - 8s 986us/step - loss: 0.3567 - acc: 0.8729 - val_loss: 0.4828 - val_acc: 0.8389
Epoch 35/80
8121/8121 [==============================] - 8s 996us/step - loss: 0.3498 - acc: 0.8740 - val_loss: 0.4614 - val_acc: 0.8453
Epoch 36/80
8121/8121 [==============================] - 8s 987us/step - loss: 0.3426 - acc: 0.8796 - val_loss: 0.4703 - val_acc: 0.8438
Epoch 37/80
8121/8121 [==============================] - 8s 989us/step - loss: 0.3307 - acc: 0.8830 - val_loss: 0.4807 - val_acc: 0.8419
Epoch 38/80
8121/8121 [==============================] - 8s 991us/step - loss: 0.3306 - acc: 0.8812 - val_loss: 0.4497 - val_acc: 0.8527
Epoch 39/80
8121/8121 [==============================] - 8s 992us/step - loss: 0.3299 - acc: 0.8785 - val_loss: 0.4726 - val_acc: 0.8404
Epoch 40/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3186 - acc: 0.8839 - val_loss: 0.4581 - val_acc: 0.8369
Epoch 41/80
2030/2030 [====================

Epoch 52/80
8121/8121 [==============================] - 8s 990us/step - loss: 0.2876 - acc: 0.8974 - val_loss: 0.4883 - val_acc: 0.8365
Epoch 53/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.2828 - acc: 0.9005 - val_loss: 0.4974 - val_acc: 0.8369
Epoch 54/80
8121/8121 [==============================] - 8s 997us/step - loss: 0.2753 - acc: 0.8966 - val_loss: 0.4554 - val_acc: 0.8433
Epoch 55/80
8121/8121 [==============================] - 8s 991us/step - loss: 0.2731 - acc: 0.8973 - val_loss: 0.4612 - val_acc: 0.8463
Epoch 56/80
8121/8121 [==============================] - 8s 994us/step - loss: 0.2715 - acc: 0.9033 - val_loss: 0.4855 - val_acc: 0.8463
Epoch 57/80
2030/2030 [==============================] - 1s 341us/step
Loss: 0.558, Accuracy: 0.839
Train on 8121 samples, validate on 2030 samples
Epoch 1/80
8121/8121 [==============================] - 11s 1ms/step - loss: 0.9997 - acc: 0.5732 - val_loss: 0.9002 - val_acc: 0.5872
Epoch 2/80
8121/8121 [============

8120/8120 [==============================] - 8s 972us/step - loss: 0.4774 - acc: 0.8256 - val_loss: 0.4995 - val_acc: 0.8173
Epoch 14/80
8120/8120 [==============================] - 8s 966us/step - loss: 0.4726 - acc: 0.8232 - val_loss: 0.5332 - val_acc: 0.8124
Epoch 15/80
8120/8120 [==============================] - 8s 984us/step - loss: 0.4624 - acc: 0.8277 - val_loss: 0.6015 - val_acc: 0.7962
Epoch 16/80
8120/8120 [==============================] - 8s 983us/step - loss: 0.4576 - acc: 0.8323 - val_loss: 0.4937 - val_acc: 0.8104
Epoch 17/80
8120/8120 [==============================] - 8s 997us/step - loss: 0.4472 - acc: 0.8381 - val_loss: 0.4953 - val_acc: 0.8163
Epoch 18/80
8120/8120 [==============================] - 8s 1ms/step - loss: 0.4401 - acc: 0.8379 - val_loss: 0.5033 - val_acc: 0.8119
Epoch 19/80
8120/8120 [==============================] - 8s 1ms/step - loss: 0.4208 - acc: 0.8490 - val_loss: 0.4990 - val_acc: 0.8282
Epoch 20/80
8120/8120 [==============================] - 

8121/8121 [==============================] - 8s 998us/step - loss: 0.4321 - acc: 0.8435 - val_loss: 0.4097 - val_acc: 0.8483
Epoch 22/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.4008 - acc: 0.8522 - val_loss: 0.4692 - val_acc: 0.8458
Epoch 23/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.4051 - acc: 0.8478 - val_loss: 0.4306 - val_acc: 0.8394
Epoch 24/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.4038 - acc: 0.8547 - val_loss: 0.4407 - val_acc: 0.8498
Epoch 25/80
8121/8121 [==============================] - 8s 999us/step - loss: 0.3927 - acc: 0.8559 - val_loss: 0.4919 - val_acc: 0.8286
Epoch 26/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3853 - acc: 0.8581 - val_loss: 0.4209 - val_acc: 0.8502
Epoch 27/80
8121/8121 [==============================] - 8s 992us/step - loss: 0.3874 - acc: 0.8574 - val_loss: 0.4309 - val_acc: 0.8404
Epoch 28/80
8121/8121 [==============================] - 8s 1

8121/8121 [==============================] - 8s 938us/step - loss: 0.3821 - acc: 0.8628 - val_loss: 0.4722 - val_acc: 0.8246
Epoch 29/80
8121/8121 [==============================] - 8s 946us/step - loss: 0.3885 - acc: 0.8600 - val_loss: 0.4613 - val_acc: 0.8355
Epoch 30/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3691 - acc: 0.8650 - val_loss: 0.4880 - val_acc: 0.8365
Epoch 31/80
8121/8121 [==============================] - 8s 948us/step - loss: 0.3633 - acc: 0.8705 - val_loss: 0.4638 - val_acc: 0.8360
Epoch 32/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3769 - acc: 0.8596 - val_loss: 0.4995 - val_acc: 0.8315
Epoch 33/80
8121/8121 [==============================] - 8s 960us/step - loss: 0.3709 - acc: 0.8615 - val_loss: 0.4790 - val_acc: 0.8468
Epoch 34/80
8121/8121 [==============================] - 8s 958us/step - loss: 0.3612 - acc: 0.8678 - val_loss: 0.4454 - val_acc: 0.8458
Epoch 35/80
8121/8121 [==============================] - 

2030/2030 [==============================] - 1s 345us/step
Loss: 0.442, Accuracy: 0.849
Train on 8121 samples, validate on 2030 samples
Epoch 1/80
8121/8121 [==============================] - 12s 1ms/step - loss: 0.9983 - acc: 0.5818 - val_loss: 0.8984 - val_acc: 0.5872
Epoch 2/80
8121/8121 [==============================] - 8s 936us/step - loss: 0.8611 - acc: 0.6214 - val_loss: 0.8623 - val_acc: 0.6493
Epoch 3/80
8121/8121 [==============================] - 8s 984us/step - loss: 0.7927 - acc: 0.6576 - val_loss: 0.7270 - val_acc: 0.6862
Epoch 4/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.7143 - acc: 0.7057 - val_loss: 0.6569 - val_acc: 0.7138
Epoch 5/80
8121/8121 [==============================] - 8s 939us/step - loss: 0.6566 - acc: 0.7364 - val_loss: 0.6112 - val_acc: 0.7557
Epoch 6/80
8121/8121 [==============================] - 8s 981us/step - loss: 0.6257 - acc: 0.7497 - val_loss: 0.6179 - val_acc: 0.7483
Epoch 7/80
8121/8121 [=============================

8121/8121 [==============================] - 8s 943us/step - loss: 0.2730 - acc: 0.9044 - val_loss: 0.5191 - val_acc: 0.8468
Epoch 60/80
8121/8121 [==============================] - 8s 970us/step - loss: 0.2688 - acc: 0.9027 - val_loss: 0.5043 - val_acc: 0.8453
Epoch 61/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.2678 - acc: 0.9052 - val_loss: 0.4953 - val_acc: 0.8463
Epoch 62/80
8121/8121 [==============================] - 8s 996us/step - loss: 0.2753 - acc: 0.9027 - val_loss: 0.4705 - val_acc: 0.8502
Epoch 63/80
8121/8121 [==============================] - 8s 994us/step - loss: 0.2564 - acc: 0.9074 - val_loss: 0.4828 - val_acc: 0.8512
Epoch 64/80
2030/2030 [==============================] - 1s 354us/step
Loss: 0.472, Accuracy: 0.843
Train on 8120 samples, validate on 2031 samples
Epoch 1/80
8120/8120 [==============================] - 12s 1ms/step - loss: 1.0044 - acc: 0.5767 - val_loss: 0.8668 - val_acc: 0.6032
Epoch 2/80
8120/8120 [========================

8120/8120 [==============================] - 8s 975us/step - loss: 0.2794 - acc: 0.9005 - val_loss: 0.5364 - val_acc: 0.8346
Epoch 55/80
2031/2031 [==============================] - 1s 358us/step
Loss: 0.519, Accuracy: 0.840
Train on 8121 samples, validate on 2030 samples
Epoch 1/80
8121/8121 [==============================] - 12s 1ms/step - loss: 0.9986 - acc: 0.5757 - val_loss: 0.9158 - val_acc: 0.5857
Epoch 2/80
8121/8121 [==============================] - 8s 958us/step - loss: 0.8654 - acc: 0.6145 - val_loss: 0.8576 - val_acc: 0.6517
Epoch 3/80
8121/8121 [==============================] - 8s 974us/step - loss: 0.7774 - acc: 0.6669 - val_loss: 0.7151 - val_acc: 0.6970
Epoch 4/80
8121/8121 [==============================] - 8s 956us/step - loss: 0.7010 - acc: 0.7087 - val_loss: 0.6603 - val_acc: 0.7695
Epoch 5/80
8121/8121 [==============================] - 8s 964us/step - loss: 0.6431 - acc: 0.7366 - val_loss: 0.5831 - val_acc: 0.7906
Epoch 6/80
8121/8121 [==========================

8121/8121 [==============================] - 8s 1ms/step - loss: 0.4640 - acc: 0.8276 - val_loss: 0.4709 - val_acc: 0.8266
Epoch 17/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.4455 - acc: 0.8381 - val_loss: 0.4537 - val_acc: 0.8414
Epoch 18/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.4458 - acc: 0.8380 - val_loss: 0.4586 - val_acc: 0.8315
Epoch 19/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.4385 - acc: 0.8368 - val_loss: 0.4447 - val_acc: 0.8448
Epoch 20/80
8121/8121 [==============================] - 8s 999us/step - loss: 0.4238 - acc: 0.8455 - val_loss: 0.4646 - val_acc: 0.8399
Epoch 21/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.4237 - acc: 0.8468 - val_loss: 0.5071 - val_acc: 0.8330
Epoch 22/80
8121/8121 [==============================] - 8s 998us/step - loss: 0.4322 - acc: 0.8452 - val_loss: 0.4349 - val_acc: 0.8458
Epoch 23/80
8121/8121 [==============================] - 8s 1ms

8121/8121 [==============================] - 8s 1ms/step - loss: 0.4177 - acc: 0.8504 - val_loss: 0.4524 - val_acc: 0.8369
Epoch 19/80
8121/8121 [==============================] - 8s 1000us/step - loss: 0.4190 - acc: 0.8467 - val_loss: 0.4718 - val_acc: 0.8350
Epoch 20/80
8121/8121 [==============================] - 8s 979us/step - loss: 0.3983 - acc: 0.8538 - val_loss: 0.4839 - val_acc: 0.8374
Epoch 21/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.4036 - acc: 0.8492 - val_loss: 0.4616 - val_acc: 0.8374
Epoch 22/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3972 - acc: 0.8585 - val_loss: 0.4540 - val_acc: 0.8360
Epoch 23/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3923 - acc: 0.8561 - val_loss: 0.4977 - val_acc: 0.8345
Epoch 24/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3822 - acc: 0.8621 - val_loss: 0.4645 - val_acc: 0.8404
Epoch 25/80
8121/8121 [==============================] - 8s 99

8121/8121 [==============================] - 8s 1ms/step - loss: 0.3858 - acc: 0.8593 - val_loss: 0.4437 - val_acc: 0.8424
Epoch 31/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3805 - acc: 0.8610 - val_loss: 0.4950 - val_acc: 0.8330
Epoch 32/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3723 - acc: 0.8637 - val_loss: 0.5498 - val_acc: 0.8256
Epoch 33/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3656 - acc: 0.8711 - val_loss: 0.4407 - val_acc: 0.8502
Epoch 34/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3611 - acc: 0.8697 - val_loss: 0.4406 - val_acc: 0.8443
Epoch 35/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3514 - acc: 0.8707 - val_loss: 0.4742 - val_acc: 0.8409
Epoch 36/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3628 - acc: 0.8697 - val_loss: 0.4364 - val_acc: 0.8542
Epoch 37/80
8121/8121 [==============================] - 8s 1ms/ste

8120/8120 [==============================] - 8s 949us/step - loss: 0.3015 - acc: 0.8922 - val_loss: 0.4808 - val_acc: 0.8464
Epoch 45/80
8120/8120 [==============================] - 8s 974us/step - loss: 0.2951 - acc: 0.8940 - val_loss: 0.4828 - val_acc: 0.8355
Epoch 46/80
8120/8120 [==============================] - 8s 990us/step - loss: 0.2906 - acc: 0.8956 - val_loss: 0.5174 - val_acc: 0.8341
Epoch 47/80
8120/8120 [==============================] - 8s 953us/step - loss: 0.2878 - acc: 0.8993 - val_loss: 0.4902 - val_acc: 0.8360
Epoch 48/80
8120/8120 [==============================] - 8s 946us/step - loss: 0.2983 - acc: 0.8904 - val_loss: 0.5300 - val_acc: 0.8262
Epoch 49/80
8120/8120 [==============================] - 8s 984us/step - loss: 0.2762 - acc: 0.8979 - val_loss: 0.4828 - val_acc: 0.8518
Epoch 50/80
8120/8120 [==============================] - 8s 967us/step - loss: 0.2866 - acc: 0.8963 - val_loss: 0.4858 - val_acc: 0.8400
Epoch 51/80
8120/8120 [==============================

8121/8121 [==============================] - 8s 958us/step - loss: 0.5470 - acc: 0.7881 - val_loss: 0.5613 - val_acc: 0.7833
Epoch 9/80
8121/8121 [==============================] - 8s 995us/step - loss: 0.5399 - acc: 0.7924 - val_loss: 0.5259 - val_acc: 0.8099
Epoch 10/80
8121/8121 [==============================] - 8s 954us/step - loss: 0.5306 - acc: 0.7936 - val_loss: 0.5300 - val_acc: 0.7951
Epoch 11/80
8121/8121 [==============================] - 8s 955us/step - loss: 0.5120 - acc: 0.8067 - val_loss: 0.5182 - val_acc: 0.8015
Epoch 12/80
8121/8121 [==============================] - 8s 992us/step - loss: 0.4989 - acc: 0.8069 - val_loss: 0.4671 - val_acc: 0.8330
Epoch 13/80
8121/8121 [==============================] - 8s 989us/step - loss: 0.4883 - acc: 0.8210 - val_loss: 0.4911 - val_acc: 0.8256
Epoch 14/80
8121/8121 [==============================] - 8s 961us/step - loss: 0.4662 - acc: 0.8280 - val_loss: 0.5079 - val_acc: 0.8261
Epoch 15/80
8121/8121 [==============================]

8121/8121 [==============================] - 8s 1ms/step - loss: 0.4067 - acc: 0.8545 - val_loss: 0.4905 - val_acc: 0.8236
Epoch 27/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3953 - acc: 0.8577 - val_loss: 0.4819 - val_acc: 0.8360
Epoch 28/80
8121/8121 [==============================] - 8s 983us/step - loss: 0.3908 - acc: 0.8588 - val_loss: 0.4502 - val_acc: 0.8414
Epoch 29/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3829 - acc: 0.8590 - val_loss: 0.4379 - val_acc: 0.8409
Epoch 30/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3841 - acc: 0.8639 - val_loss: 0.4463 - val_acc: 0.8399
Epoch 31/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3823 - acc: 0.8572 - val_loss: 0.4754 - val_acc: 0.8246
Epoch 32/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3719 - acc: 0.8653 - val_loss: 0.4508 - val_acc: 0.8389
Epoch 33/80
8121/8121 [==============================] - 8s 1ms/s

8121/8121 [==============================] - 8s 963us/step - loss: 0.3554 - acc: 0.8713 - val_loss: 0.4658 - val_acc: 0.8350
Epoch 33/80
8121/8121 [==============================] - 8s 981us/step - loss: 0.3561 - acc: 0.8746 - val_loss: 0.4461 - val_acc: 0.8458
Epoch 34/80
8121/8121 [==============================] - 8s 958us/step - loss: 0.3459 - acc: 0.8739 - val_loss: 0.4471 - val_acc: 0.8453
Epoch 35/80
8121/8121 [==============================] - 8s 979us/step - loss: 0.3423 - acc: 0.8770 - val_loss: 0.4665 - val_acc: 0.8517
Epoch 36/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3490 - acc: 0.8732 - val_loss: 0.4750 - val_acc: 0.8399
Epoch 37/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3417 - acc: 0.8807 - val_loss: 0.4646 - val_acc: 0.8443
Epoch 38/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3324 - acc: 0.8825 - val_loss: 0.4609 - val_acc: 0.8419
Epoch 39/80
8121/8121 [==============================] - 8s

8120/8120 [==============================] - 8s 1ms/step - loss: 0.3761 - acc: 0.8653 - val_loss: 0.4846 - val_acc: 0.8360
Epoch 30/80
8120/8120 [==============================] - 8s 1ms/step - loss: 0.3698 - acc: 0.8693 - val_loss: 0.4775 - val_acc: 0.8296
Epoch 31/80
8120/8120 [==============================] - 8s 1ms/step - loss: 0.3740 - acc: 0.8658 - val_loss: 0.4667 - val_acc: 0.8262
Epoch 32/80
8120/8120 [==============================] - 8s 1ms/step - loss: 0.3711 - acc: 0.8676 - val_loss: 0.4953 - val_acc: 0.8360
Epoch 33/80
8120/8120 [==============================] - 8s 1ms/step - loss: 0.3647 - acc: 0.8697 - val_loss: 0.5083 - val_acc: 0.8277
Epoch 34/80
8120/8120 [==============================] - 8s 1ms/step - loss: 0.3682 - acc: 0.8683 - val_loss: 0.4752 - val_acc: 0.8370
Epoch 35/80
8120/8120 [==============================] - 8s 990us/step - loss: 0.3717 - acc: 0.8665 - val_loss: 0.4844 - val_acc: 0.8208
Epoch 36/80
8120/8120 [==============================] - 8s 986us

8121/8121 [==============================] - 8s 986us/step - loss: 0.3515 - acc: 0.8711 - val_loss: 0.4704 - val_acc: 0.8502
Epoch 41/80
8121/8121 [==============================] - 8s 962us/step - loss: 0.3491 - acc: 0.8722 - val_loss: 0.4279 - val_acc: 0.8488
Epoch 42/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3377 - acc: 0.8778 - val_loss: 0.4316 - val_acc: 0.8522
Epoch 43/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3384 - acc: 0.8772 - val_loss: 0.4366 - val_acc: 0.8488
Epoch 44/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3443 - acc: 0.8780 - val_loss: 0.4610 - val_acc: 0.8448
Epoch 45/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3310 - acc: 0.8787 - val_loss: 0.4316 - val_acc: 0.8453
Epoch 46/80
2030/2030 [==============================] - 1s 432us/step
Loss: 0.531, Accuracy: 0.810
Train on 8121 samples, validate on 2030 samples
Epoch 1/80
8121/8121 [============================

8121/8121 [==============================] - 8s 991us/step - loss: 0.5197 - acc: 0.8038 - val_loss: 0.5318 - val_acc: 0.8128
Epoch 11/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.5013 - acc: 0.8110 - val_loss: 0.4851 - val_acc: 0.8212
Epoch 12/80
8121/8121 [==============================] - 8s 972us/step - loss: 0.4940 - acc: 0.8186 - val_loss: 0.5431 - val_acc: 0.7901
Epoch 13/80
8121/8121 [==============================] - 8s 991us/step - loss: 0.4908 - acc: 0.8211 - val_loss: 0.4870 - val_acc: 0.8167
Epoch 14/80
8121/8121 [==============================] - 8s 987us/step - loss: 0.4556 - acc: 0.8319 - val_loss: 0.4634 - val_acc: 0.8291
Epoch 15/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.4627 - acc: 0.8309 - val_loss: 0.4838 - val_acc: 0.8222
Epoch 16/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.4498 - acc: 0.8357 - val_loss: 0.4941 - val_acc: 0.8177
Epoch 17/80
8121/8121 [==============================] - 8s

8121/8121 [==============================] - 8s 989us/step - loss: 0.8740 - acc: 0.6047 - val_loss: 0.8350 - val_acc: 0.6286
Epoch 3/80
8121/8121 [==============================] - 8s 984us/step - loss: 0.8223 - acc: 0.6408 - val_loss: 0.7843 - val_acc: 0.6685
Epoch 4/80
8121/8121 [==============================] - 8s 977us/step - loss: 0.7444 - acc: 0.6855 - val_loss: 0.7323 - val_acc: 0.7217
Epoch 5/80
8121/8121 [==============================] - 8s 988us/step - loss: 0.6821 - acc: 0.7199 - val_loss: 0.6311 - val_acc: 0.7532
Epoch 6/80
8121/8121 [==============================] - 8s 991us/step - loss: 0.6427 - acc: 0.7353 - val_loss: 0.6235 - val_acc: 0.7453
Epoch 7/80
8121/8121 [==============================] - 8s 975us/step - loss: 0.6165 - acc: 0.7497 - val_loss: 0.6061 - val_acc: 0.7655
Epoch 8/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.5915 - acc: 0.7638 - val_loss: 0.5634 - val_acc: 0.7798
Epoch 9/80
8121/8121 [==============================] - 8s 95

8120/8120 [==============================] - 8s 1ms/step - loss: 0.4323 - acc: 0.8416 - val_loss: 0.4892 - val_acc: 0.8227
Epoch 19/80
8120/8120 [==============================] - 8s 997us/step - loss: 0.4225 - acc: 0.8437 - val_loss: 0.5019 - val_acc: 0.8099
Epoch 20/80
8120/8120 [==============================] - 8s 987us/step - loss: 0.4193 - acc: 0.8430 - val_loss: 0.5189 - val_acc: 0.8149
Epoch 21/80
8120/8120 [==============================] - 8s 990us/step - loss: 0.4191 - acc: 0.8496 - val_loss: 0.4804 - val_acc: 0.8203
Epoch 22/80
8120/8120 [==============================] - 8s 969us/step - loss: 0.3966 - acc: 0.8578 - val_loss: 0.4681 - val_acc: 0.8282
Epoch 23/80
8120/8120 [==============================] - 8s 999us/step - loss: 0.3972 - acc: 0.8553 - val_loss: 0.4728 - val_acc: 0.8331
Epoch 24/80
8120/8120 [==============================] - 8s 982us/step - loss: 0.3882 - acc: 0.8591 - val_loss: 0.4669 - val_acc: 0.8434
Epoch 25/80
8120/8120 [==============================] 

8121/8121 [==============================] - 8s 990us/step - loss: 0.3905 - acc: 0.8596 - val_loss: 0.4520 - val_acc: 0.8443
Epoch 28/80
8121/8121 [==============================] - 8s 965us/step - loss: 0.3959 - acc: 0.8601 - val_loss: 0.4355 - val_acc: 0.8424
Epoch 29/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3940 - acc: 0.8558 - val_loss: 0.4733 - val_acc: 0.8291
Epoch 30/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3931 - acc: 0.8584 - val_loss: 0.4234 - val_acc: 0.8547
Epoch 31/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3756 - acc: 0.8628 - val_loss: 0.4270 - val_acc: 0.8414
Epoch 32/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3881 - acc: 0.8562 - val_loss: 0.4325 - val_acc: 0.8419
Epoch 33/80
8121/8121 [==============================] - 8s 983us/step - loss: 0.3774 - acc: 0.8658 - val_loss: 0.4290 - val_acc: 0.8443
Epoch 34/80
8121/8121 [==============================] - 8s 9

8121/8121 [==============================] - 8s 965us/step - loss: 0.3415 - acc: 0.8753 - val_loss: 0.5005 - val_acc: 0.8399
Epoch 37/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3407 - acc: 0.8739 - val_loss: 0.5160 - val_acc: 0.8305
Epoch 38/80
8121/8121 [==============================] - 8s 973us/step - loss: 0.3384 - acc: 0.8780 - val_loss: 0.4692 - val_acc: 0.8502
Epoch 39/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3434 - acc: 0.8758 - val_loss: 0.4997 - val_acc: 0.8300
Epoch 40/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3226 - acc: 0.8844 - val_loss: 0.4821 - val_acc: 0.8433
Epoch 41/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3281 - acc: 0.8824 - val_loss: 0.4963 - val_acc: 0.8330
Epoch 42/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3202 - acc: 0.8831 - val_loss: 0.5004 - val_acc: 0.8335
Epoch 43/80
8121/8121 [==============================] - 8s 1ms

8121/8121 [==============================] - 8s 988us/step - loss: 0.3972 - acc: 0.8577 - val_loss: 0.4604 - val_acc: 0.8315
Epoch 31/80
8121/8121 [==============================] - 8s 1000us/step - loss: 0.3883 - acc: 0.8595 - val_loss: 0.4644 - val_acc: 0.8369
Epoch 32/80
8121/8121 [==============================] - 8s 972us/step - loss: 0.3897 - acc: 0.8594 - val_loss: 0.4520 - val_acc: 0.8424
Epoch 33/80
8121/8121 [==============================] - 8s 966us/step - loss: 0.3703 - acc: 0.8674 - val_loss: 0.4948 - val_acc: 0.8251
Epoch 34/80
8121/8121 [==============================] - 8s 974us/step - loss: 0.3809 - acc: 0.8623 - val_loss: 0.4372 - val_acc: 0.8350
Epoch 35/80
8121/8121 [==============================] - 8s 990us/step - loss: 0.3720 - acc: 0.8650 - val_loss: 0.4783 - val_acc: 0.8300
Epoch 36/80
8121/8121 [==============================] - 8s 966us/step - loss: 0.3631 - acc: 0.8714 - val_loss: 0.4637 - val_acc: 0.8325
Epoch 37/80
8121/8121 [=============================

8121/8121 [==============================] - 8s 981us/step - loss: 0.3899 - acc: 0.8568 - val_loss: 0.4558 - val_acc: 0.8350
Epoch 36/80
8121/8121 [==============================] - 8s 995us/step - loss: 0.3652 - acc: 0.8661 - val_loss: 0.4505 - val_acc: 0.8335
Epoch 37/80
8121/8121 [==============================] - 8s 963us/step - loss: 0.3491 - acc: 0.8718 - val_loss: 0.4417 - val_acc: 0.8478
Epoch 38/80
8121/8121 [==============================] - 8s 960us/step - loss: 0.3620 - acc: 0.8655 - val_loss: 0.5045 - val_acc: 0.8291
Epoch 39/80
8121/8121 [==============================] - 8s 962us/step - loss: 0.3508 - acc: 0.8682 - val_loss: 0.4668 - val_acc: 0.8369
Epoch 40/80
8121/8121 [==============================] - 8s 998us/step - loss: 0.3618 - acc: 0.8717 - val_loss: 0.4915 - val_acc: 0.8315
Epoch 41/80
8121/8121 [==============================] - 8s 970us/step - loss: 0.3488 - acc: 0.8742 - val_loss: 0.4964 - val_acc: 0.8256
Epoch 42/80
8121/8121 [==============================

8120/8120 [==============================] - 8s 1ms/step - loss: 0.3386 - acc: 0.8746 - val_loss: 0.4712 - val_acc: 0.8272
Epoch 33/80
8120/8120 [==============================] - 8s 1ms/step - loss: 0.3489 - acc: 0.8719 - val_loss: 0.4620 - val_acc: 0.8316
Epoch 34/80
8120/8120 [==============================] - 8s 1ms/step - loss: 0.3428 - acc: 0.8723 - val_loss: 0.4814 - val_acc: 0.8247
Epoch 35/80
8120/8120 [==============================] - 8s 1ms/step - loss: 0.3760 - acc: 0.8601 - val_loss: 0.4816 - val_acc: 0.8301
Epoch 36/80
8120/8120 [==============================] - 8s 984us/step - loss: 0.3311 - acc: 0.8772 - val_loss: 0.4713 - val_acc: 0.8267
Epoch 37/80
8120/8120 [==============================] - 8s 1ms/step - loss: 0.3908 - acc: 0.8564 - val_loss: 0.5013 - val_acc: 0.8163
Epoch 38/80
8120/8120 [==============================] - 8s 974us/step - loss: 0.3351 - acc: 0.8784 - val_loss: 0.4630 - val_acc: 0.8291
Epoch 39/80
8120/8120 [==============================] - 8s 983

8121/8121 [==============================] - 15s 2ms/step - loss: 1.0210 - acc: 0.5600 - val_loss: 0.8843 - val_acc: 0.5931
Epoch 2/80
8121/8121 [==============================] - 8s 978us/step - loss: 0.8994 - acc: 0.6014 - val_loss: 0.8256 - val_acc: 0.6291
Epoch 3/80
8121/8121 [==============================] - 8s 996us/step - loss: 0.7930 - acc: 0.6579 - val_loss: 0.7577 - val_acc: 0.6961
Epoch 4/80
8121/8121 [==============================] - 8s 969us/step - loss: 0.6930 - acc: 0.7114 - val_loss: 0.6636 - val_acc: 0.7241
Epoch 5/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.6430 - acc: 0.7355 - val_loss: 0.6109 - val_acc: 0.7473
Epoch 6/80
8121/8121 [==============================] - 8s 976us/step - loss: 0.6089 - acc: 0.7500 - val_loss: 0.5973 - val_acc: 0.7759
Epoch 7/80
8121/8121 [==============================] - 8s 961us/step - loss: 0.5489 - acc: 0.7903 - val_loss: 0.5247 - val_acc: 0.7946
Epoch 8/80
8121/8121 [==============================] - 8s 998

8121/8121 [==============================] - 8s 989us/step - loss: 0.4605 - acc: 0.8303 - val_loss: 0.5088 - val_acc: 0.8128
Epoch 17/80
8121/8121 [==============================] - 8s 971us/step - loss: 0.4689 - acc: 0.8322 - val_loss: 0.4468 - val_acc: 0.8399
Epoch 18/80
8121/8121 [==============================] - 8s 967us/step - loss: 0.4572 - acc: 0.8345 - val_loss: 0.4631 - val_acc: 0.8296
Epoch 19/80
8121/8121 [==============================] - 8s 965us/step - loss: 0.4369 - acc: 0.8416 - val_loss: 0.4498 - val_acc: 0.8345
Epoch 20/80
8121/8121 [==============================] - 8s 970us/step - loss: 0.4417 - acc: 0.8377 - val_loss: 0.5423 - val_acc: 0.8010
Epoch 21/80
8121/8121 [==============================] - 8s 986us/step - loss: 0.4261 - acc: 0.8437 - val_loss: 0.4573 - val_acc: 0.8246
Epoch 22/80
8121/8121 [==============================] - 8s 971us/step - loss: 0.4520 - acc: 0.8293 - val_loss: 0.4822 - val_acc: 0.8281
Epoch 23/80
8121/8121 [==============================

8121/8121 [==============================] - 8s 1ms/step - loss: 0.4308 - acc: 0.8418 - val_loss: 0.4588 - val_acc: 0.8325
Epoch 20/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.4266 - acc: 0.8455 - val_loss: 0.4887 - val_acc: 0.8266
Epoch 21/80
8121/8121 [==============================] - 8s 976us/step - loss: 0.4216 - acc: 0.8464 - val_loss: 0.4683 - val_acc: 0.8345
Epoch 22/80
8121/8121 [==============================] - 8s 994us/step - loss: 0.4287 - acc: 0.8399 - val_loss: 0.5411 - val_acc: 0.8064
Epoch 23/80
8121/8121 [==============================] - 8s 995us/step - loss: 0.4012 - acc: 0.8521 - val_loss: 0.4446 - val_acc: 0.8340
Epoch 24/80
8121/8121 [==============================] - 8s 996us/step - loss: 0.4135 - acc: 0.8482 - val_loss: 0.4471 - val_acc: 0.8399
Epoch 25/80
8121/8121 [==============================] - 8s 975us/step - loss: 0.3954 - acc: 0.8527 - val_loss: 0.4738 - val_acc: 0.8251
Epoch 26/80
8121/8121 [==============================] - 

2031/2031 [==============================] - 1s 394us/step
Loss: 0.469, Accuracy: 0.839
Train on 8121 samples, validate on 2030 samples
Epoch 1/80
8121/8121 [==============================] - 16s 2ms/step - loss: 1.0193 - acc: 0.5732 - val_loss: 0.8872 - val_acc: 0.5857
Epoch 2/80
8121/8121 [==============================] - 8s 958us/step - loss: 0.8862 - acc: 0.6058 - val_loss: 0.8294 - val_acc: 0.6192
Epoch 3/80
8121/8121 [==============================] - 8s 978us/step - loss: 0.8124 - acc: 0.6441 - val_loss: 0.7491 - val_acc: 0.6611
Epoch 4/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.7282 - acc: 0.6902 - val_loss: 0.6525 - val_acc: 0.7315
Epoch 5/80
8121/8121 [==============================] - 8s 969us/step - loss: 0.6845 - acc: 0.7184 - val_loss: 0.5979 - val_acc: 0.7601
Epoch 6/80
8121/8121 [==============================] - 8s 978us/step - loss: 0.6382 - acc: 0.7402 - val_loss: 0.6271 - val_acc: 0.7448
Epoch 7/80
8121/8121 [=============================

8121/8121 [==============================] - 8s 1ms/step - loss: 0.4540 - acc: 0.8360 - val_loss: 0.4766 - val_acc: 0.8335
Epoch 17/80
8121/8121 [==============================] - 8s 977us/step - loss: 0.4258 - acc: 0.8441 - val_loss: 0.4381 - val_acc: 0.8453
Epoch 18/80
8121/8121 [==============================] - 8s 965us/step - loss: 0.4250 - acc: 0.8424 - val_loss: 0.4736 - val_acc: 0.8360
Epoch 19/80
8121/8121 [==============================] - 8s 975us/step - loss: 0.4164 - acc: 0.8448 - val_loss: 0.4700 - val_acc: 0.8325
Epoch 20/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.4196 - acc: 0.8505 - val_loss: 0.4926 - val_acc: 0.8286
Epoch 21/80
8121/8121 [==============================] - 8s 971us/step - loss: 0.4180 - acc: 0.8493 - val_loss: 0.4694 - val_acc: 0.8286
Epoch 22/80
8121/8121 [==============================] - 8s 981us/step - loss: 0.4015 - acc: 0.8541 - val_loss: 0.4304 - val_acc: 0.8527
Epoch 23/80
8121/8121 [==============================] - 

8121/8121 [==============================] - 8s 991us/step - loss: 0.3652 - acc: 0.8692 - val_loss: 0.4812 - val_acc: 0.8350
Epoch 34/80
8121/8121 [==============================] - 8s 1000us/step - loss: 0.3641 - acc: 0.8710 - val_loss: 0.4759 - val_acc: 0.8478
Epoch 35/80
8121/8121 [==============================] - 8s 981us/step - loss: 0.3567 - acc: 0.8726 - val_loss: 0.4655 - val_acc: 0.8330
Epoch 36/80
8121/8121 [==============================] - 8s 983us/step - loss: 0.3465 - acc: 0.8737 - val_loss: 0.4668 - val_acc: 0.8355
Epoch 37/80
8121/8121 [==============================] - 8s 995us/step - loss: 0.3451 - acc: 0.8738 - val_loss: 0.4743 - val_acc: 0.8325
Epoch 38/80
8121/8121 [==============================] - 8s 981us/step - loss: 0.3324 - acc: 0.8772 - val_loss: 0.4650 - val_acc: 0.8419
Epoch 39/80
8121/8121 [==============================] - 8s 973us/step - loss: 0.3464 - acc: 0.8742 - val_loss: 0.4785 - val_acc: 0.8389
Epoch 40/80
8121/8121 [=============================

8121/8121 [==============================] - 8s 1ms/step - loss: 0.3702 - acc: 0.8654 - val_loss: 0.4848 - val_acc: 0.8394
Epoch 33/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3624 - acc: 0.8710 - val_loss: 0.4475 - val_acc: 0.8522
Epoch 34/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3559 - acc: 0.8724 - val_loss: 0.4501 - val_acc: 0.8502
Epoch 35/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3569 - acc: 0.8717 - val_loss: 0.4434 - val_acc: 0.8438
Epoch 36/80
8121/8121 [==============================] - 8s 995us/step - loss: 0.3447 - acc: 0.8742 - val_loss: 0.4963 - val_acc: 0.8315
Epoch 37/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3469 - acc: 0.8698 - val_loss: 0.5029 - val_acc: 0.8315
Epoch 38/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3391 - acc: 0.8754 - val_loss: 0.4411 - val_acc: 0.8527
Epoch 39/80
2030/2030 [==============================] - 1s 469us

8121/8121 [==============================] - 8s 977us/step - loss: 0.7994 - acc: 0.6502 - val_loss: 0.7589 - val_acc: 0.6419
Epoch 4/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.7207 - acc: 0.6908 - val_loss: 0.6627 - val_acc: 0.7187
Epoch 5/80
8121/8121 [==============================] - 8s 975us/step - loss: 0.6671 - acc: 0.7264 - val_loss: 0.6429 - val_acc: 0.7601
Epoch 6/80
8121/8121 [==============================] - 8s 977us/step - loss: 0.6202 - acc: 0.7486 - val_loss: 0.5527 - val_acc: 0.7680
Epoch 7/80
8121/8121 [==============================] - 8s 974us/step - loss: 0.5983 - acc: 0.7653 - val_loss: 0.5653 - val_acc: 0.7813
Epoch 8/80
8121/8121 [==============================] - 8s 999us/step - loss: 0.5820 - acc: 0.7700 - val_loss: 0.5034 - val_acc: 0.8192
Epoch 9/80
8121/8121 [==============================] - 8s 994us/step - loss: 0.5512 - acc: 0.7882 - val_loss: 0.5049 - val_acc: 0.8030
Epoch 10/80
8121/8121 [==============================] - 8s 9

8121/8121 [==============================] - 8s 978us/step - loss: 0.4539 - acc: 0.8324 - val_loss: 0.4854 - val_acc: 0.8158
Epoch 16/80
8121/8121 [==============================] - 8s 972us/step - loss: 0.4487 - acc: 0.8324 - val_loss: 0.4624 - val_acc: 0.8340
Epoch 17/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.4360 - acc: 0.8402 - val_loss: 0.4607 - val_acc: 0.8172
Epoch 18/80
8121/8121 [==============================] - 8s 989us/step - loss: 0.4401 - acc: 0.8402 - val_loss: 0.4713 - val_acc: 0.8300
Epoch 19/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.4246 - acc: 0.8444 - val_loss: 0.4866 - val_acc: 0.8222
Epoch 20/80
8121/8121 [==============================] - 8s 999us/step - loss: 0.4208 - acc: 0.8473 - val_loss: 0.4981 - val_acc: 0.8271
Epoch 21/80
8121/8121 [==============================] - 8s 985us/step - loss: 0.4236 - acc: 0.8412 - val_loss: 0.4535 - val_acc: 0.8374
Epoch 22/80
8121/8121 [==============================] - 

8121/8121 [==============================] - 8s 1ms/step - loss: 0.3792 - acc: 0.8590 - val_loss: 0.4402 - val_acc: 0.8502
Epoch 27/80
8121/8121 [==============================] - 8s 977us/step - loss: 0.3630 - acc: 0.8663 - val_loss: 0.4509 - val_acc: 0.8389
Epoch 28/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3711 - acc: 0.8617 - val_loss: 0.4518 - val_acc: 0.8429
Epoch 29/80
8121/8121 [==============================] - 8s 997us/step - loss: 0.3630 - acc: 0.8718 - val_loss: 0.4402 - val_acc: 0.8468
Epoch 30/80
8121/8121 [==============================] - 8s 975us/step - loss: 0.3499 - acc: 0.8762 - val_loss: 0.4651 - val_acc: 0.8305
Epoch 31/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3469 - acc: 0.8686 - val_loss: 0.4498 - val_acc: 0.8443
Epoch 32/80
8121/8121 [==============================] - 8s 994us/step - loss: 0.3561 - acc: 0.8660 - val_loss: 0.4652 - val_acc: 0.8389
Epoch 33/80
8121/8121 [==============================] - 8s

8121/8121 [==============================] - 8s 983us/step - loss: 0.4047 - acc: 0.8552 - val_loss: 0.4241 - val_acc: 0.8463
Epoch 27/80
8121/8121 [==============================] - 8s 973us/step - loss: 0.3865 - acc: 0.8610 - val_loss: 0.4605 - val_acc: 0.8365
Epoch 28/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3975 - acc: 0.8527 - val_loss: 0.4401 - val_acc: 0.8419
Epoch 29/80
8121/8121 [==============================] - 8s 998us/step - loss: 0.3856 - acc: 0.8599 - val_loss: 0.4708 - val_acc: 0.8296
Epoch 30/80
8121/8121 [==============================] - 8s 982us/step - loss: 0.3959 - acc: 0.8567 - val_loss: 0.4599 - val_acc: 0.8433
Epoch 31/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3767 - acc: 0.8620 - val_loss: 0.4279 - val_acc: 0.8443
Epoch 32/80
8121/8121 [==============================] - 8s 1ms/step - loss: 0.3820 - acc: 0.8637 - val_loss: 0.4287 - val_acc: 0.8473
Epoch 33/80
8121/8121 [==============================] - 8s

In [5]:
# for bat, lr in itertools.product(batch_S, learning_rate):
#     print(bat, lr)

In [6]:
import pprint
pprint.pprint(F1_result)

[array([0.78210692, 0.58941757, 0.90392228, 0.7522676 ]),
 array([0.79159909, 0.57669239, 0.90442679, 0.75448937]),
 array([0.76905081, 0.60450842, 0.90390831, 0.74750219]),
 array([0.76697001, 0.56622316, 0.90381395, 0.75523637]),
 array([0.80460213, 0.58552474, 0.90165807, 0.75286997]),
 array([0.7871668 , 0.56380356, 0.90283217, 0.74980707]),
 array([0.77751363, 0.5896029 , 0.90055801, 0.74005806]),
 array([0.76775888, 0.59426933, 0.90397249, 0.75388005]),
 array([0.76576212, 0.61504999, 0.90192391, 0.73725381]),
 array([0.77258374, 0.6046346 , 0.90345956, 0.74703007]),
 array([0.7989271 , 0.59520712, 0.90492798, 0.74554438])]


In [7]:
# array([0.79250755, 0.62614335, 0.90266635, 0.74891516])