In [1]:
import numpy as np
from sklearn.model_selection import KFold
from keras.utils import np_utils
trainD = np.load("/home/hsiehch/30s/train_data.npy")
trainL = np.load("/home/hsiehch/30s/train_label.npy")
validationD = np.load("/home/hsiehch/30s/validation_data.npy")
validationL = np.load("/home/hsiehch/30s/validation_label.npy")
testD = np.load("/home/hsiehch/30s/test_data.npy")
testL = np.load("/home/hsiehch/30s/test_label.npy")

trainD = np.append(trainD, validationD, axis=0)
trainL = np.append(trainL, validationL, axis=0)
trainD = np.append(trainD, testD, axis=0)
trainL = np.append(trainL, testL, axis=0)

trainData = trainD.reshape((trainD.shape[0], trainD.shape[1], 1))
trainLabel = np_utils.to_categorical(trainL, 4)
print('Train Data:', trainData.shape)
print('Train Label: ', trainLabel.shape)

kf = KFold(n_splits=5, shuffle=True)
print(kf)

training_data = []
training_label = []
validation_cate_label = []
validation_data = []
validation_label = []

for train_index, test_index in kf.split(trainData):
    print('trian:', train_index, 'len', len(train_index), 'test:', test_index, 'len', len(test_index))
    training_data.append(trainData[train_index])
    training_label.append(trainLabel[train_index])
    validation_data.append(trainData[test_index])
    validation_label.append(trainLabel[test_index])
    validation_cate_label.append(trainL[test_index])

training_data = np.array(training_data)
training_label = np.array(training_label)
validation_data = np.array(validation_data)
validation_label = np.array(validation_label)
validation_cate_label = np.array(validation_cate_label)

Using TensorFlow backend.


Train Data: (10151, 9000, 1)
Train Label:  (10151, 4)
KFold(n_splits=5, random_state=None, shuffle=True)
trian: [    1     2     3 ... 10147 10148 10149] len 8120 test: [    0    12    32 ... 10129 10143 10150] len 2031
trian: [    0     1     3 ... 10148 10149 10150] len 8121 test: [    2    10    14 ... 10136 10139 10140] len 2030
trian: [    0     2     3 ... 10148 10149 10150] len 8121 test: [    1    15    22 ... 10145 10146 10147] len 2030
trian: [    0     1     2 ... 10147 10148 10150] len 8121 test: [    7    11    13 ... 10141 10144 10149] len 2030
trian: [    0     1     2 ... 10147 10149 10150] len 8121 test: [    3     4     5 ... 10132 10135 10148] len 2030


In [9]:
sum(training_label[0])

array([ 741.,  228., 4780., 2371.], dtype=float32)

In [10]:
sum(validation_label[0])

array([ 162.,   71., 1179.,  619.], dtype=float32)

In [2]:
sum(training_label[1])

array([ 737.,  239., 4766., 2379.], dtype=float32)

In [3]:
sum(validation_label[1])

array([ 166.,   60., 1193.,  611.], dtype=float32)